import { status } from "@grpc/grpc-js";
import { ELLIPSIS } from "@spacedb/core/core-constants";
import type { IRevision } from "@spacedb/core/i-revision";
import type { Relationship } from "@spacedb/core/relationship";
import type { RelationshipUpdate } from "@spacedb/core/relationship-update";
import { decodeRevision, zedTokenFromRevision } from "@spacedb/core/zed-tokens";
import {
  RevisionNotFoundException,
  WatchDisabledException,
} from "@spacedb/datastore/datastore-exceptions";
import type { IDatastore } from "@spacedb/datastore/i-datastore";
import type { RevisionChange, WatchContent, WatchOptions } from "@spacedb/datastore/watch";
import { WatchContent as WatchContentFlags } from "@spacedb/datastore/watch";
import type { ISchemaProvider } from "@spacedb/grains/i-schema-provider";
import type {
  Relationship as ProtoRelationship,
  RelationshipUpdate as ProtoRelationshipUpdate,
  WatchRequest,
  WatchResponse,
} from "@spacedb/protos/permissions";
import { RelationshipUpdate_Operation, WatchKind } from "@spacedb/protos/permissions";
import { isCancellationError } from "@thresh/core/errors";

import { RpcError } from "./rpc-error";
import type { ServerStreamWriter } from "./server-stream-writer";

/** Nanoseconds per second: core carries an expiration as epoch nanos, the proto as unix seconds. */
const NANOS_PER_SECOND = 1_000_000_000n;

/**
 * Port of Spiceport `src/Spiceport.Api/WatchGrpcService.cs`: the `spiceport.v0` gRPC front door for
 * the relationship + schema changefeed. Server-streaming Watch consumes the silo-singleton
 * `IDatastore.watch` directly rather than going through a grain: a long-lived server stream is a
 * poor fit for a request/response (stateless-worker) grain, and the datastore is already a
 * process-wide singleton, so the method simply tails its `AsyncIterable` and writes each change to
 * the response stream. Each emitted response carries its own ZedToken so a client can resume
 * exactly once after a disconnect.
 *
 * Port decisions (the C# constructs with no TypeScript counterpart):
 *   * The `(request, IServerStreamWriter<T>, ServerCallContext)` signature becomes
 *     `(request, ServerStreamWriter<T>, AbortSignal | undefined)` - see
 *     {@link ServerStreamWriter}. Node stream backpressure lives in the `program.ts` adapter.
 *   * `GetAsyncEnumerator` / `MoveNextAsync` / `DisposeAsync` becomes a MANUAL
 *     `[Symbol.asyncIterator]()` / `next()` / `return?.()` loop, not `for await`: the loop must
 *     distinguish cancellation from the two FAILED_PRECONDITION exceptions and must re-check the
 *     signal between the move and the write, and `for await` allows neither.
 *   * `catch (OperationCanceledException)` becomes `isCancellationError`, matched on the TYPE and
 *     never on a message string.
 *   * `RpcException(new Status(code, detail))` becomes {@link RpcError}.
 *   * `optional_expires_at_unix_seconds` is a ts-proto STRING (`forceLong=string`), so it renders
 *     through `String(nanos / 1_000_000_000n)` - never a JS `number`.
 */
export class WatchGrpcService {
  readonly #datastore: IDatastore;
  readonly #schemaProvider: ISchemaProvider;

  constructor(datastore: IDatastore, schemaProvider: ISchemaProvider) {
    this.#datastore = datastore;
    this.#schemaProvider = schemaProvider;
  }

  /** Tails the datastore changefeed, writing one response per revision change. */
  async watch(
    request: WatchRequest,
    responseStream: ServerStreamWriter<WatchResponse>,
    signal?: AbortSignal | undefined,
  ): Promise<void> {
    const content = resolveContent(request);

    // Resolve the start cursor: a supplied token decodes to its revision (rejecting a mismatched
    // datastore); otherwise start from current head so only future writes are tailed.
    let afterRevision: IRevision;
    const cursor = request.optionalStartCursor;
    if (cursor !== undefined && cursor.token.length > 0) {
      const parser = await this.#datastore.getRevisionParser(signal);
      const decoded = decodeRevision({ token: cursor.token }, parser);
      if (decoded.status === "mismatchedDatastoreId") {
        throw new RpcError(
          status.INVALID_ARGUMENT,
          "start cursor was generated by a different datastore instance",
        );
      }
      if (decoded.status === "unknown") {
        throw new RpcError(status.INVALID_ARGUMENT, "invalid start cursor");
      }
      afterRevision = decoded.revision;
    } else {
      const head = await this.#datastore.headRevision(signal);
      afterRevision = head.revision;
    }

    const datastoreId = await this.#datastore.getUniqueId(signal);
    const options: WatchOptions = { content };

    // The datastore watch is a lazy iterator: cursor-validity and watch-enablement checks throw on
    // the first `next()`, not at `[Symbol.asyncIterator]()` (an async-generator body does not run
    // until the first `next()` call), so the catch must wrap the iteration, not the iterator
    // creation.
    const stream = this.#datastore.watch(afterRevision, options, signal);
    const enumerator = stream[Symbol.asyncIterator]();

    try {
      for (;;) {
        let moved: IteratorResult<RevisionChange>;
        try {
          moved = await enumerator.next();
        } catch (error) {
          if (isCancellationError(error)) {
            break;
          }
          if (error instanceof RevisionNotFoundException) {
            // The cursor is older than the retained GC window - cannot replay from it.
            throw new RpcError(status.FAILED_PRECONDITION, error.message);
          }
          if (error instanceof WatchDisabledException) {
            // The backend cannot support Watch (e.g. Postgres without track_commit_timestamp=on).
            throw new RpcError(status.FAILED_PRECONDITION, error.message);
          }
          throw error;
        }

        if (moved.done === true) {
          break;
        }

        if (signal?.aborted === true) {
          break;
        }

        const change = moved.value;
        // Per-write cancellation is not supported by the writer seam; the loop and the iterator's
        // `next()` already observe the call's cancellation signal.
        await responseStream.write(this.#toResponse(change, datastoreId));
      }
    } finally {
      await enumerator.return?.();
    }
  }

  /** `ToResponse`: mints this revision's ZedToken from the CURRENT schema hash, read per response. */
  #toResponse(change: RevisionChange, datastoreId: string): WatchResponse {
    const token = zedTokenFromRevision(
      change.revision,
      this.#schemaProvider.current.schemaHash,
      datastoreId,
    );
    const response: WatchResponse = {
      updates: [],
      changesThrough: { token: token.token },
      schemaUpdated: change.schemaChanged ?? false,
    };

    for (const update of change.relationshipChanges) {
      response.updates.push(toProtoUpdate(update));
    }

    return response;
  }
}

/**
 * `ResolveContent`: an empty kind list is relationships; otherwise the flags are OR-ed, with
 * INCLUDE_SCHEMA_UPDATES mapping to schema and EVERYTHING ELSE (UNSPECIFIED and
 * INCLUDE_RELATIONSHIP_UPDATES included) to relationships.
 */
function resolveContent(request: WatchRequest): WatchContent {
  if (request.optionalUpdateKinds.length === 0) {
    return WatchContentFlags.relationships;
  }

  let content = 0;
  for (const kind of request.optionalUpdateKinds) {
    content |=
      kind === WatchKind.WATCH_KIND_INCLUDE_SCHEMA_UPDATES
        ? WatchContentFlags.schema
        : WatchContentFlags.relationships;
  }
  return content;
}

/** `ToProto(RelationshipUpdate)`: anything that is not create/delete is a TOUCH. */
function toProtoUpdate(update: RelationshipUpdate): ProtoRelationshipUpdate {
  const op =
    update.operation === "create"
      ? RelationshipUpdate_Operation.OPERATION_CREATE
      : update.operation === "delete"
        ? RelationshipUpdate_Operation.OPERATION_DELETE
        : RelationshipUpdate_Operation.OPERATION_TOUCH;
  return { operation: op, relationship: toProtoRelationship(update.relationship) };
}

/** `ToProto(Relationship)`, blanking an ellipsis subject relation. */
function toProtoRelationship(rel: Relationship): ProtoRelationship {
  const resource = rel.reference.resource;
  const subject = rel.reference.subject;
  const subjectRelation = subject.relation === ELLIPSIS ? "" : subject.relation;
  const proto: ProtoRelationship = {
    resource: { objectType: resource.objectType, objectId: resource.objectId },
    resourceRelation: resource.relation,
    subject: {
      object: { objectType: subject.objectType, objectId: subject.objectId },
      optionalRelation: subjectRelation,
    },
    // BigInt division truncates toward ZERO where `ToUnixTimeSeconds` floors: the two differ only
    // for a sub-second pre-1970 expiration.
    optionalExpiresAtUnixSeconds:
      rel.optionalExpiration !== undefined
        ? String(rel.optionalExpiration / NANOS_PER_SECOND)
        : "0",
  };

  const caveat = rel.optionalCaveat;
  if (caveat !== undefined) {
    const pc: { caveatName: string; context?: { [key: string]: unknown } | undefined } = {
      caveatName: caveat.caveatName,
    };
    const ctx = mapToStruct(caveat.context);
    if (ctx !== undefined) {
      pc.context = ctx;
    }
    proto.optionalCaveat = pc;
  }

  return proto;
}

/** `DictToStruct`: an absent or EMPTY dictionary is `undefined` (C# `null`). */
function mapToStruct(
  dict: ReadonlyMap<string, unknown> | undefined,
): { [key: string]: unknown } | undefined {
  if (dict === undefined || dict.size === 0) {
    return undefined;
  }

  // A NULL-PROTOTYPE object, not `{}`: C# writes into `Struct.Fields`, an ordinary dictionary,
  // so a key called `__proto__` is stored like any other. On an object literal that same
  // assignment hits the inherited setter on `Object.prototype` and the key vanishes with no
  // error - silent loss of an input to an authorization decision.
  const s = Object.create(null) as { [key: string]: unknown };
  for (const [k, v] of dict) {
    s[k] = objectToValue(v);
  }
  return s;
}

/**
 * `ObjectToValue`. THE ORDER OF THE BRANCHES IS THE BEHAVIOUR: the C# matches `string` before
 * `IEnumerable` and `IReadOnlyDictionary` before `IEnumerable`, and in TypeScript a string is
 * itself iterable, so a string tested after the list branch would be exploded into characters.
 *
 * A `bigint` has no C# counterpart at all (`int`/`long`/`double` all collapse to `ForNumber`), so
 * it deliberately takes the `o.ToString()` fallback rather than a lossy `Number(...)`.
 *
 * The C# keeps a private copy of this block per gRPC service; the port keeps that duplication
 * rather than lifting a shared module the source does not have.
 */
function objectToValue(o: unknown): unknown {
  if (o === null || o === undefined) return null;
  if (typeof o === "boolean") return o;
  if (typeof o === "string") return o;
  if (typeof o === "number") return o;
  if (o instanceof Map) return mapToStruct(o as ReadonlyMap<string, unknown>) ?? {};
  if (Array.isArray(o)) return o.map(objectToValue);
  return String(o);
}
